### ISSUE TITLE
Ordering of display files and default selection

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#105]
Using our test compendium Aquestiondrivenprocess, the extractor creates the following metadata (excerpt):

```json
[...]
"raw": {
"mainfile_candidates": [
"shFun.R",
"multiplot.R",
"Ui.R",
"LaunchModel.R",
"main.Rmd",
"server.R"
],
"mainfile": "main.Rmd",
"displayfile_candidates": [
"figure89.png",
"figure2.png",
"figure3.png",
"table1.png",
"display.html",
"figure4.png",
"figure6.png",
"figure5.png",
"table4.png",
"table2.png",
"table5.png",
"figure1.png",
"table3.png"
],
"displayfile": "figure89.png",
[...]
```

In the display files, it should prefer

- HTML over png
- file named "display" over any other file

The existing files:

![image](https://user-images.githubusercontent.com/1325054/39308779-9a588da4-4966-11e8-9188-fb09ef583c47.png)

@7048730 can you confirm the function [`best_candidate`](https://github.com/o2r-project/o2r-meta/blob/3f9fb513b2a0b539c7db3ed53d17f2b2c92b90be/extract/metaextract.py#L32) currently only works for mainfiles, and that function must be extended for displayfiles?

**Comment by 7048730** [comment]
@nuest just to clarify: do you want to have an ordered list as a result or do you want to keep out less suitable candidates? (**this concerns the displayfiles list**)

The `best_candidate` function is neither used for mainfiles nor for displayfiles explicitly, but instead completes all gathered metadata elements in a single list. for example if half of the relevant elements is found in one file and the rest in another during extraction. So it generates a competitive scenario for the most complex or complete information on each element extracted (**this concerns all files encountered during extraction**)

It might be a good idea to rewrite a more generic generation of `best_candidate`. The code is not very sophisticated either, since I built this around everchanging requirements from the frontend guys 😃  ☮️

**Comment by nuest** [comment]
Ordered list.

Does the ordered list then also fix the default `displayfile`, i.e. what is first in the list is then used?

**Comment by 7048730** [comment]
yes, this edit distance thing. might result in e.g. `play.html` getting higher rank than `display.jpeg`.
I think we should go the easy way and keep splitting the name and extension and then rank all things we can anticipate. do magic with the rest
