### ISSUE TITLE
Wrong path to main file

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-meta#23]
In the `o2r`-attribute, the subattribute `file` contains metadata about the main file. There, `filepath` is missing one `/data` subfolder.
Example:
```
{
o2r: {
        file: {
                 filepath: 'Oh0ZA/data/main.Rmd'
               }
        }
}
```
Instead, it should be:
```
{
o2r: {
        file: {
                 filepath: 'Oh0ZA/data/data/main.Rmd'
               }
        }
}
```

**Comment by 7048730** [comment]
could write api paths instead of file system paths in `o2r.file.filepath` MD, so the frontend can directly take these to render the files
@nuest We might want to replace the content butler's keyword "data" to avoid multiple "data" in api paths when working with bagits. though that would be only for aestetics. 

- [ ] discussed with group and agreed to the suggested changes

**Comment by nuest** [comment]
@7048730 I am fine with updating the API path... suggestions?

- `_`
- `content`
- `files`

**Comment by 7048730** [comment]
I'd prefer `files` because `_` is not a word and `content` is a word thats gets overlooked easily :)

**Comment by 7048730** [comment]
Can we close this? will you update the content butler / the api parts?
