### ISSUE TITLE
Required property identifier is not further defined in the o2r schema; ercIdentifier to be removed

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#92]
https://github.com/o2r-project/o2r-meta/blob/master/schema/json/o2r-meta-schema.json#L41

Shouldn't the structure of the required property `identifier` be further defined?
What about `ercIdentifier` - is it used somewhere? Imho it could be removed.

**Comment by 7048730** [comment]
`identifier`: is a subelement of `depends` meaning "name". It was called "identifier" because codemeta uses that name of a similar element.
`ercIdentifier`: As far as I know, it is no longer in use, except in old examples and maps where is could go obsolete with no consequences.

**Comment by nuest** [comment]
Ok, let's remove `ercIdentifier` then.

I included the wrong link, sorry! I actually mean _this_ `identifier`: https://github.com/o2r-project/o2r-meta/blob/master/schema/json/o2r-meta-schema.json#L135

**Comment by 7048730** [comment]
That identifier element holds the persistent identifiers, e.g.

```json
    "identifier": {
        "doi": "10.5555/666655554444",
        "doiurl": "https://doi.org/10.5555/666655554444",
        "reserveddoi": null
    }
```

We cannot know what specific identifiers will be included, although we use `doi` as de facto default. But a 3rd party repository could use a `handle` identifier exclusively. There is a lot of other persistent identifiers which could be used here exclusively or in combination with each other. That's why I would advise to keep the subelements undefined. Newer versions of json schema have the `contain` key word, which can be used to create controlled lists in order to require at least one element of several possiblities.

**Comment by nuest** [comment]
I'm OK with not defining the top level `identifier` further with your arguments in mind.

AFAICS this issue can be closed after `ercIdentifier` is removed.

**Comment by 7048730** [comment]
ercIdentifier will be removed with https://github.com/o2r-project/o2r-meta/pull/93
